#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the plusMinus function below.
def plusMinus(arr):
    po_count=0
    ne_count =0
    zero_count=0
    for i in range (len(arr)):
     if(arr[i]>0):
        po_count+=1
   
     elif(arr[i]<0):
        ne_count+=1
     else:
        zero_count+=1

    a=po_count/n;
    b=ne_count/n;
    c=zero_count/n;
    print(a)
    print(b)
    print(c)
if __name__ == '__main__':
    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
