#!/bin/python3
import os
import sys

#
# Complete the timeConversion function below.
#
def timeConversion(s):
    #
    # Write your code here.
    #
   hour =int(s[:2])

   meridian=s[8:]
   rem=(s[2:8])
   if(meridian=="AM"):
   
      if(hour==12):
        hour="0"
   if(meridian=="PM"):
       if(hour<12):
         hour+=12
       r=str(hour)+str(rem)
       return r


   else:
      r="0"+str(hour)+str(rem)
      return r
  
if __name__ == '__main__':
    f = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()
    
    result = timeConversion(s)
    print (result)
    f.write(result + '\n')

    f.close()
